name = "Brewgo"
license = "MIT"
licenselink = "https://github.com/cgbaker/brewgo/blob/master/LICENSE"
description = "An adaptation of the Beautiful Hugo theme for Breweries"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
features = ["blog", "company", "portfolio", "projects", "minimal", "responsive", "seo", "google analytics", "bootstrap", "disqus", "light", "syntax highlighting", "multilingual", "portfolio", "projects", "mobile", "technical"]
min_version = "0.124.0"

[author]
    name = "cgbaker"
    homepage = "https://github.com/cgbaker/brewgo"

# If Porting existing theme
[original]
    author = "halogenica"
    homepage = "https://halogenica.net"
    repo = "https://github.com/halogenica/beautifulhugo"
